### ISSUE TITLE
Redefine and adjust vertical offsets

### ISSUE THREAD

**Issue by pichfl** [mainmatter/mainmatter.com#315]
The goal of this issue is to provide a base for a vertical rhythm for the website. This may require manual fine tuning, but it should work as a baseline.

Important: This does not change or touch any horizontal values. I'll re-evaluate those in a separate issue if necessary.

The idea of having a vertical rhythm comes from classic typography and uses a base value and multiples of it to describe possible distances between elements.

We need to do this in two steps: 
1. Define line-heights that fit into this rhythm
2. Define vertical offsets (for margin/padding) which are multiples of the base value as well.

All pixel values in this ticket are measured for a screen width of `1440px+`

Our new base value will be `8`.

I do recommend defining everything based on `rem` over `em` as this makes nesting much easier. I also recommend defining the root font-size as a percentage value for maximum accessibility (so browsers can scale the page based on the font size. Setting a pixel value removes that option) 

```css
html { font-size: 100%; /* === 16px */ }
body { font-size: 50%; /* === 16 / 2 * 100 */ }
```

### Font scale 

| Name | font-size/line-height | in rem |
| --- | --- | --- |
| Display 1 | 80px/96px | 10rem/12rem |
| Headline 1 | 64px/80px | 8rem/10rem |
| Headline 2 | 40px/48px | 5rem/6rem |
| Headline 3 | 32px/40px | 4rem/5rem |
| Paragraph Lead | 32px/48px | 4rem/6rem |
| Paragraph | 24px/40px | 3rem/5rem |
| Navigation | 16px/24px | 2rem/3rem |
| Paragraph Small | 16px/24px | 2rem/3rem |

### Vertical offset scale

| Size in pixel | in rem |
| --- | --- |
| 16px | 2rem |
| 24px | 3rem |
| 40px | 5rem |
| 48px | 6rem |
| 64px | 8rem |
| 96px | 12rem |
| 128px | 16rem |
| 224px | 28rem |

We could consider defining the offsets as multipliers of their base value, making it possible to readjust them for other screen sizes

```css
:root { 
  --offset-scale-y1: 2;
  --offset-scale-y2: 3;
  --offset-scale-y4: 5;
  --offset-scale-y5: 6;
  /* ... and so on */

  --offset-y0: 0;
  --offset-y1: calc(1rem * var(--offset-scale-y1));
  --offset-y2: calc(1rem * var(--offset-scale-y2));
  --offset-y3: calc(1rem * var(--offset-scale-y3));
  --offset-y4: calc(1rem * var(--offset-scale-y4));
  --offset-y5: calc(1rem * var(--offset-scale-y5));
  /* ... */
}

@media (max-width: 1023px) {
  :root { 
      --offset-scale-y1: 2;
      --offset-scale-y2: 3;
      --offset-scale-y4: 4;
      --offset-scale-y5: 4
      /* ... */
  }
}

/* In use */
.container {
  padding: var(--offset-y5) 0;
}
```

- `em`-based sizes are found across the project. I do recommend refactoring to `rem` where sensible.
- We could consider moving the base unit of `1rem` to `8px` at `1440px` width.

**Edit:** Comment updated after deciding to move to base 8. May the refactoring begin.
